apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-cluster
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v16.2.1
  resources:
    osd:
      limits:
        cpu: "4"
        memory: "6Gi"
      requests:
        cpu: "2"
        memory: "4Gi"
  storage:
    useAllDevices: false
    deviceFilter: ^sd[b-c]