apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kfserving/config/overlays/kubeflow?ref=v0.6.1

images:
- name: gcr.io/kfserving/kfserving-controller
  newName: gcr.io/kfserving/kfserving-controller
  newTag: v0.6.1
  # digest: sha256:e54ccd9fda78a02c6f7c8e37494a7500a9741549e20f8d74fb73b4da79468cdb
