apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: kubeflow-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  roleArn: <<__role_arn.external_secrets.istio_system__>>
  data:
    - key: <<__external_secret_name.istio_system.gateway_ca_cert__>>
      name: ca.crt
    - key: <<__external_secret_name.istio_system.gateway_cert__>>
      name: tls.crt
    - key: <<__external_secret_name.istio_system.gateway_cert_pk__>>
      name: tls.key
