apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - github.com/metallb/metallb/manifests?ref=2233271f768663a9a52e9ef629867f3aa3f30833 # tag=v0.9.6
  - configmap.yaml 
  - secret.yaml

images:
- name: metallb/controller
  newName: metallb/controller
  newTag: v0.10.2
  # digest: sha256:99b79462af3d8b7d3b18dd31b854148b9d05365843d2c69ce7c3dd8a1f0d015d
- name: metallb/speaker
  newName: metallb/speaker
  newTag: v0.9.6
  # digest: sha256:dffdaee85e79393785f98f7fd7666fa7d9f53fd90d3319c59a622911ca2e0a09
