apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubecost.github.io/cost-analyzer/
    targetRevision: 1.81.0
    chart: cost-analyzer
    helm:
     parameters:
      - name: global.podAnnotations.sidecar\.istio\.io\/inject
        value: \"false\"
      - name: global.prometheus.enabled
        value: "false"
      - name: global.prometheus.kubeStateMetrics.enabled
        value: "false"
      - name: global.prometheus.fqdn
        value: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      - name: serviceMonitor.enabled
        value: "true"
      - name: prometheusRule.enabled
        value: "true"
      - name: global.grafana.enabled
        value: "false"
      - name: global.grafana.domainName
        value: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
      - name: kubecostProductConfigs.grafanaURL
        value: https://<<__subdomain_grafana__>>.<<__domain__>>/grafana
        # Placing the dashboards into a folder is not working yet.
        # Dashboards are also slighlty broken so might be better to use versions we fixed
      # - name: grafana.sidecar.dashboards.annotations.k8s-sidecar-target-directory
      #   value: /tmp/dashboards/kubecost
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
