apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
    path: distribution/oidc-auth/overlays/dex
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
