apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/DavidSpek/kubeflow/components/crud-web-apps/volumes/manifests/overlays/istio?ref=volumes-pvc-viewer

images:
- name: davidspek/volumes-web-app
  newName: davidspek/volumes-web-app
  newTag: "0.5.4"
  # digest: sha256:0b80a09e878f9dcdd530da7948155d532c61f7ad9ce854e7fa26440ade720d8c
