apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "tjwfoViioOyg8x+gg20q+n4n5AMI1ECzCiuvlEubN08pWAXG1mg2jgYUWAsnG2ZJ\nhCosGiq/e1zKETfFg87LBq2crFzM/1Vq0kd+bSLzsNAyvZ9NA5d+gTa38Izbgho/\nBusLPgZ/eZCgConRIQ33Y/N4l+58XCodm0gq/y3ipgA="
