apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "+B4xLMdMBkdWOdp8BC8iXk1Aow1q+OqaTh8n153qhjS+V9NcjP7BOzDiArS9MoC6\nQBfOq4ASSvDl1PskOGWcflUo+lzHoCaPNLnD7vOpCQZj4isWImVy3KMYFu8F8+xD\n+qcaNKw3IocXI4Bc1LAOl0H2BqOnKzpmMWGzuTIVLBA="
