apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/profile-controller/config/overlays/kubeflow?ref=v1.4.0 # tag=v1.4.0

patchesStrategicMerge:
  - patch-admin.yaml

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newName: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newTag: v1.4
- name: public.ecr.aws/j1r0q0g6/notebooks/profile-controller
  newName: public.ecr.aws/j1r0q0g6/notebooks/profile-controller
  newTag: v1.4
