apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/notebook-controller/config/overlays/kubeflow?ref=0e91a2b9cd0c3b6687692b1f1f09ac6070cc6c3e # tag=v1.3.0

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newTag: v1.3.0
