apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/notebook-controller/config/overlays/kubeflow?ref=v1.4.0 # tag=v1.4.0

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newTag: v1.4
  # digest: sha256:cac3ed9a9826a518d838ce4872d9d7094b3670ba632d1df537c32ea38515e4cb